name: Code Style

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: cs2pr

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: PHPCS check
        run: ./vendor/bin/phpcs -q --report=checkstyle src | cs2pr

  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Run phpstan
        run: composer analyse
